duka/urls.py
from django.urls import path
from . import views
app_name ='duka'
urlpatterns = [
    path('', views.home, name='home'),
    path('mycart/', views.cartPage, name='cart'),
    path('product/', views.shopGrid, name='shop'),
    path('contact/', views.Contact, name='contact'),
    path('product/<int:id>/',views.product, name='details'),
    path('add-to-cart/<int:id>/',views.AddToCart, name='cart_add'),
    path('remove-from-cart/<int:id>/',views.removeFromCart, name='cart_remove'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('update-profile/',views.updateProfile, name='update-profile'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('duka.urls',namespace='duka')),
    path('orders/',include('orders.urls', namespace = 'orders')),
    path('coupon/',include('coupon.urls',namespace='coupon'))
]

urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

orders/urls.py
from django.urls import path
from . import views


app_name ='orders'
urlpatterns = [
    path('checkout/',views.checkout, name='checkout'),
    path('admin/order/<int:order_id>/pdf/',views.GeneratePdf,name='admin_order_pdf'),
    path('confirm/<int:order_id>/Order/',views.order_invoice,name='send_invoice'),

]

duka/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.forms import ModelForm
from coupon.models import Coupon



CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
    ('C', 'Cars'),
    ('G', 'Groceries'),
    ('B','Beer'),
    ('SH','Shoes')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(User,
                             on_delete=models.CASCADE,null=True)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(blank=True,max_length=20)
    city = models.CharField(blank=True,max_length=20)
    
    def __str__(self):
        return self.phone


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    available = models.BooleanField(default=True)
    additional_info=models.TextField(max_length=300,blank=True)
    quantity_available = models.IntegerField(default=1)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('duka:details',args=[self.id])
    def get_add_url(self):
        return reverse('duka:cart_add',args=[self.id])
    def get_remove_url(self):
        return reverse('duka:cart_remove',args=[self.id])
   
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url 

class ContactMessage(models.Model):
    STATUS =(
        ('New','New'),
        ('Read','Read'),
    )
    name = models.CharField(max_length=200)
    email =models.EmailField(max_length=50,blank=True,null=True)
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=500)
    status = models.CharField(choices=STATUS,default='New',max_length=30)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name','email','subject','message']

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    product = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity= models.IntegerField(default=1)
   

    
    def __str__(self):
        return self.product.title
  

    @property
    def price(self):
        return self.product.price
    
    @property
    def amount(self):
        if self.product.discount_price:
            return self.quantity * self.product.discount_price
        else:
            return self.quantity * self.product.price

    
class CartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['quantity']

templates/home-page.html
{% extends 'base.html' %}


{% block content %}

<body>


  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls ="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-2">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in items%}
          <div class="col-lg-4 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{item.imageUrl}} " class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{item.get_absolute_url}} " class="grey-text">
                  <h5>{{item.get_category_display}} </h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">{{item.title}} </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">

                  <strong>
                    {% if item.discount_price %}
                    {{item.discount_price}} $
                    {% else %}
                    {{item.price}}
                    {% endif %}
                  </strong>
                </h4>
				          <a class="btn btn-outline-success" href="#">View</a>
				          
                <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}
          

        </div>
        <!--Grid row-->
        <div class="col-lg-4 col-md-6 mb-4">
      
          <div class="single-product">
            <div class="product-img">
              <a href="product-details.html">
                <img class="default-img" src="https://via.placeholder.com/550x750" alt="#">
                <img class="hover-img" src="https://via.placeholder.com/550x750" alt="#">
                <span class="new">New</span>
              </a>
              <div class="button-head">
                <div class="product-action">
                  <a data-toggle="modal" data-target="#exampleModal" title="Quick View" href="#"><i class="fas fa-eye"></i><span>Quick Shop</span></a>
                  <a title="Wishlist" href="#"><i class="fas fa-chart-bar"></i><span>Add to Wishlist</span></a>
                  <a title="Compare" href="#"><i class="ti-bar-chart-alt"></i><span>Add to Compare</span></a>
                </div>
                <div class="product-action-2">
                  <a title="Add to cart" href="#">Add to cart</a>
                </div>
              </div>
            </div>
            <div class="product-content">
              <h3><a href="product-details.html">Women Pant Collectons</a></h3>
              <div class="product-price">
                <span>$29.00</span>
              </div>
            </div>
          </div>
        </div>

        


         
      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}

templates/nav.html
{% load static %}
{% static "images" as baseUrl %}
	<!-- Header -->
	<header class="header shop">
		<!-- Topbar -->
		<div class="topbar">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-12 col-12">
						<!-- Top Left -->
						<div class="top-left">
							<ul class="list-main">
								<li><i class="ti-headphone-alt"></i> +254 714-212-473</li>
								<li><i class="ti-email"></i> clanx@gmail.com</li>
							</ul>
						</div>
						<!--/ End Top Left -->
					</div>
					<div class="col-lg-8 col-md-12 col-12">
						<!-- Top Right -->
						<div class="right-content">
							<ul class="list-main">
								<li><i class="ti-location-pin"></i> Store location</li>
						         {% if user.is_authenticated%}
								<li><i class="ti-user"></i> <a href="{% url 'duka:update-profile' %}">Welcome {{user.username}}</a></li>
								<li><i class="ti-user"></i> <a href="{% url 'duka:logout' %}">Logout</a></li>
								{% else%}
								<li><i class="ti-power-off"></i><a href="{% url 'duka:login' %}">Login</a></li>
								{% endif %}
							</ul>
						</div>
						<!-- End Top Right -->
					</div>
				</div>
			</div>
		</div>
		<!-- End Topbar -->
		<div class="middle-inner">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 col-md-2 col-12">
						<!-- Logo -->
							<!-- Logo -->
						<div class="logo">
							<h2>JaneMart</h2>
						</div>
						<!--/ End Logo -->
						<!-- Search Form -->
						<div class="search-top">
							<div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
							<!-- Search Form -->
							<div class="search-top">
								<form class="search-form">
									<input type="text" placeholder="Search here..." name="search">
									<button value="search" type="submit"><i class="ti-search"></i></button>
								</form>
							</div>
							<!--/ End Search Form -->
						</div>
						<!--/ End Search Form -->
						<div class="mobile-nav"></div>
					</div>
					<div class="col-lg-8 col-md-7 col-12">
						<div class="search-bar-top">
							<div class="search-bar">
								<select>
									<option selected="selected">All Category</option>
									<option>watch</option>
									<option>mobile</option>
									<option>kid’s item</option>
								</select>
								<form>
									<input name="search" placeholder="Search Products Here....." type="search">
									<button class="btnn"><i class="ti-search"></i></button>
								</form>
							</div>
						</div>
					</div>
					<div class="col-lg-2 col-md-3 col-12">
						<div class="right-bar">
						
							<!-- Search Form -->
							<div class="sinlge-bar">
								<a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
							</div>
							<div class="sinlge-bar">
								<a href="{% url 'duka:update-profile' %}" class="single-icon"><i class="fa fa-user-circle-o"></i></a>
							</div>
							<div class="sinlge-bar shopping">
								<a href="{% url 'duka:cart' %}" class="single-icon">
									<i class="fa fa-cart-plus" style="font-size:36px"></i><span style="background-color: rgb(121, 15, 197);" class="total-count">{{vo}}</span></a>
							</div>
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Header Inner -->
		<div class="header-inner">
			<div class="container">
				<div class="cat-nav-head">
					<div class="row">
						<div class="col-12">
							<div class="menu-area">
								<!-- Main Menu -->
								<nav class="navbar navbar-expand-lg">
									<div class="navbar-collapse">	
										<div class="nav-inner">	
											<ul class="nav main-menu menu navbar-nav">
												<li class="active"><a href="{% url 'duka:home' %}">Home</a></li>
												<li><a href="{% url 'duka:shop' %}">Products</a></li>
												<li><a href="{% url 'orders:checkout' %}">Checkout</a></li>
												<li><a href="{% url 'duka:cart' %}">Cart</a></li>											
												<li><a href="{% url 'duka:contact' %}">Contact Us</a></li>
												
											</ul>
										</div>
									</div>
								</nav>
								<!--/ End Main Menu -->	
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/ End Header Inner -->
	</header>

templates/pdf.html
{% load static %}
{% static 'img' as baseUrl %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>ClanB</title>
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <title>Invoice</title>
</head>
<style>
    #tbs{
		background-color: whitesmoke;
	
        color: indigo;
		padding: 4px 4px;
		
	}
	.main-hading{
		font-size: 14px;
		background-color: indigo;
		color: white;
	}
	#top{
		color: indigo;
		text-shadow: 2px 2px 2px burlywood;
		font-size: 30px;
		font-weight: bolder;
		font-style: italic;
	}

</style>
<body>
	<h1 id="top">OnyiShop</h1>
	<div style="margin-left: 550px;">
		<p><span style="font-weight: bold;">OnyiShop Kenya</span> <br>
			<span class="secondary">
			Contacts:071421473,
			</span><br>
			<span>Email: info@OnyiShop.com,</span><br>
			<span>Nairobi,Kenya</span><br>
			<span>www.OnyiShop.com</span><br>
			<span></span><br>
		
		</p>
	</div>
    <div class="manu">
		<div>
			<h2>INVOICE</h2>
			<p>Invoice no.  OnyiShop-1998{{ order.id }}<br>
				<span class="secondary">
				{{ order.ordered_date|date:"M d, Y" }}
				</span><br>
				<span>{{order.first_name}} {{order.last_name}}</span><br>
				<span>{{order.city}}</span><br>
				<span>{{order.email}}</span><br>
				<span>{{order.phone}}</span>
			</p>
		</div>
	
	</div>
	
    	<!-- Shopping Cart -->
	<div class="shopping-cart section">
		<div class="container">
			<div class="row" >
				<div class="col-12" >
					<!-- Shopping Summery -->
					<table class="table shopping-summery" id="tbs">
						<thead>
							<tr class="main-hading">
								<th>PRODUCT</th>
								
								<th class="text-center">UNIT PRICE</th>
								<th class="text-center">QUANTITY</th>
								<th class="text-center">SUB-TOTAL</th> 
								
							</tr>
						</thead>
						<tbody style="background-color: white;">
							{% for item in items %}			
							<tr>
								<td class="product-des" data-title="Description" style="text-align: center;">
									<p class="product-name">{{item.product.title}}</p>
									
								</td>
								<td class="price" data-title="Price" style="text-align: center;"><span>Ksh {{item.price}}</span></td>
								<td class="qty" data-title="Qty"><!-- Input Order -->
								  <div style="text-align: center;">
									  {{item.quantity}}
								  </div>
								</td>
								<td class="total-amount" data-title="Total" style="text-align: center;"><span>Ksh {{item.amount}}</span></td>
							</tr>
							
                            {% endfor %}
						</tbody>
					
					</table> 
					<table class="table shopping-summery" id="tbs">
						
						<tbody style="background-color: white;">
							<tr class="main-hading">
								<!-- <th>PRODUCT</th>
								
								<th class="text-center">UNIT PRICE</th>
								<th class="text-center">QUANTITY</th>
								<th class="text-center">TOTAL</th>  -->
								<td class="text-center">
									TOTAL 
								</td>
								<td>

								</td>
								<td style="margin-left: 100px;">
									Ksh {{order.total_payable}}
								</td>
								
								
							</tr>
					
						</tbody>
					
					</table> 
				
					<!--/ End Shopping Summery -->
				</div>
            </div>
           
	</div>
    
</body>
</html>

templates/profile.html
{% extends 'base.html' %}
{% block content %}
<!-- Breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="bread-inner">
					<ul class="bread-list">
						<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
						<li class="active"><a href="blog-single.html">Profile</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Breadcrumbs -->
<section class="shop checkout section">
	<div class="container">
		<div class="row"> 
			<div class="col-lg-8 col-12">
				<div class="checkout-form">
					<h2 style="margin-bottom: 20px;">Your Profile </h2>
					
					<!-- Form -->
					<form class="form" method="post" action="">
                        {% csrf_token %}
						<div class="row">
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-group">
									<label>First Name<span>*</span></label>
									<input type="text" name="name" placeholder="" required="required" value="{{user.first_name}}">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-group">
									<label>Last Name<span>*</span></label>
									<input type="text" name="name" placeholder="" required="required" value="{{user.last_name}}">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-group">
									<label>Email Address<span>*</span></label>
									<input type="email" name="email" placeholder="" required="required" value="{{user.email}}">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-group">
									<label>Phone Number<span>*</span></label>
									<input type="number" name="number" placeholder="" required="required" value="{{profile.phone}}">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-group">
									<label>Country<span>*</span></label>
									<select name="country_name" id="country">
										<option>Kenya</option>
									</select>
									
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-group">
									<label>City/Town<span>*</span></label>
									<input type="text" name="state-province" value="{{profile.city}}">
								
								</div>
                            </div>
                            <div  class="col-lg-6 col-md-6 col-12 ">
                                <div class=" button">
                                    <input type="submit" class="btn btn-black" style="color: white;" name='register'value="update profile">
                                </div>

                            </div>
                            <div class="single-widget get-button">
								<div class="content">
									<div class="button">
										<a href="{% url 'duka:shop' %}" class="btn">Go Shopping</a>
									</div>
								</div>
							</div>
                            
                            
						
							
							
						
						</div>
					</form>
					<!--/ End Form -->
				</div>
			</div>
			
		</div>
	</div>
</section>
	

{% endblock %}